// flow-typed signature: ea00331970d0f7742d385469b62176a1
// flow-typed version: <<STUB>>/@tandem.ly/react-scripts_v^1.0.19/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@tandem.ly/react-scripts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@tandem.ly/react-scripts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@tandem.ly/react-scripts/bin/react-scripts' {
  declare module.exports: any;
}

declare module '@tandem.ly/react-scripts/config/env' {
  declare module.exports: any;
}

declare module '@tandem.ly/react-scripts/config/jest/babelTransform' {
  declare module.exports: any;
}

declare module '@tandem.ly/react-scripts/config/jest/cssTransform' {
  declare module.exports: any;
}

declare module '@tandem.ly/react-scripts/config/jest/fileTransform' {
  declare module.exports: any;
}

declare module '@tandem.ly/react-scripts/config/paths' {
  declare module.exports: any;
}

declare module '@tandem.ly/react-scripts/config/polyfills' {
  declare module.exports: any;
}

declare module '@tandem.ly/react-scripts/config/webpack.config.dev' {
  declare module.exports: any;
}

declare module '@tandem.ly/react-scripts/config/webpack.config.prod' {
  declare module.exports: any;
}

declare module '@tandem.ly/react-scripts/config/webpackDevServer.config' {
  declare module.exports: any;
}

declare module '@tandem.ly/react-scripts/scripts/build' {
  declare module.exports: any;
}

declare module '@tandem.ly/react-scripts/scripts/eject' {
  declare module.exports: any;
}

declare module '@tandem.ly/react-scripts/scripts/init' {
  declare module.exports: any;
}

declare module '@tandem.ly/react-scripts/scripts/start' {
  declare module.exports: any;
}

declare module '@tandem.ly/react-scripts/scripts/test' {
  declare module.exports: any;
}

declare module '@tandem.ly/react-scripts/scripts/utils/createJestConfig' {
  declare module.exports: any;
}

declare module '@tandem.ly/react-scripts/template/src/App' {
  declare module.exports: any;
}

declare module '@tandem.ly/react-scripts/template/src/App.test' {
  declare module.exports: any;
}

declare module '@tandem.ly/react-scripts/template/src/index' {
  declare module.exports: any;
}

declare module '@tandem.ly/react-scripts/template/src/registerServiceWorker' {
  declare module.exports: any;
}

// Filename aliases
declare module '@tandem.ly/react-scripts/bin/react-scripts.js' {
  declare module.exports: $Exports<'@tandem.ly/react-scripts/bin/react-scripts'>;
}
declare module '@tandem.ly/react-scripts/config/env.js' {
  declare module.exports: $Exports<'@tandem.ly/react-scripts/config/env'>;
}
declare module '@tandem.ly/react-scripts/config/jest/babelTransform.js' {
  declare module.exports: $Exports<'@tandem.ly/react-scripts/config/jest/babelTransform'>;
}
declare module '@tandem.ly/react-scripts/config/jest/cssTransform.js' {
  declare module.exports: $Exports<'@tandem.ly/react-scripts/config/jest/cssTransform'>;
}
declare module '@tandem.ly/react-scripts/config/jest/fileTransform.js' {
  declare module.exports: $Exports<'@tandem.ly/react-scripts/config/jest/fileTransform'>;
}
declare module '@tandem.ly/react-scripts/config/paths.js' {
  declare module.exports: $Exports<'@tandem.ly/react-scripts/config/paths'>;
}
declare module '@tandem.ly/react-scripts/config/polyfills.js' {
  declare module.exports: $Exports<'@tandem.ly/react-scripts/config/polyfills'>;
}
declare module '@tandem.ly/react-scripts/config/webpack.config.dev.js' {
  declare module.exports: $Exports<'@tandem.ly/react-scripts/config/webpack.config.dev'>;
}
declare module '@tandem.ly/react-scripts/config/webpack.config.prod.js' {
  declare module.exports: $Exports<'@tandem.ly/react-scripts/config/webpack.config.prod'>;
}
declare module '@tandem.ly/react-scripts/config/webpackDevServer.config.js' {
  declare module.exports: $Exports<'@tandem.ly/react-scripts/config/webpackDevServer.config'>;
}
declare module '@tandem.ly/react-scripts/scripts/build.js' {
  declare module.exports: $Exports<'@tandem.ly/react-scripts/scripts/build'>;
}
declare module '@tandem.ly/react-scripts/scripts/eject.js' {
  declare module.exports: $Exports<'@tandem.ly/react-scripts/scripts/eject'>;
}
declare module '@tandem.ly/react-scripts/scripts/init.js' {
  declare module.exports: $Exports<'@tandem.ly/react-scripts/scripts/init'>;
}
declare module '@tandem.ly/react-scripts/scripts/start.js' {
  declare module.exports: $Exports<'@tandem.ly/react-scripts/scripts/start'>;
}
declare module '@tandem.ly/react-scripts/scripts/test.js' {
  declare module.exports: $Exports<'@tandem.ly/react-scripts/scripts/test'>;
}
declare module '@tandem.ly/react-scripts/scripts/utils/createJestConfig.js' {
  declare module.exports: $Exports<'@tandem.ly/react-scripts/scripts/utils/createJestConfig'>;
}
declare module '@tandem.ly/react-scripts/template/src/App.js' {
  declare module.exports: $Exports<'@tandem.ly/react-scripts/template/src/App'>;
}
declare module '@tandem.ly/react-scripts/template/src/App.test.js' {
  declare module.exports: $Exports<'@tandem.ly/react-scripts/template/src/App.test'>;
}
declare module '@tandem.ly/react-scripts/template/src/index.js' {
  declare module.exports: $Exports<'@tandem.ly/react-scripts/template/src/index'>;
}
declare module '@tandem.ly/react-scripts/template/src/registerServiceWorker.js' {
  declare module.exports: $Exports<'@tandem.ly/react-scripts/template/src/registerServiceWorker'>;
}
