// flow-typed signature: a81a776add03a0b36d728295e42b811b
// flow-typed version: <<STUB>>/@tandem.ly/redux-persist-transform-encrypt_v^2.0.1/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@tandem.ly/redux-persist-transform-encrypt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@tandem.ly/redux-persist-transform-encrypt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@tandem.ly/redux-persist-transform-encrypt/async' {
  declare module.exports: any;
}

declare module '@tandem.ly/redux-persist-transform-encrypt/lib/async' {
  declare module.exports: any;
}

declare module '@tandem.ly/redux-persist-transform-encrypt/lib/AsyncCryptor' {
  declare module.exports: any;
}

declare module '@tandem.ly/redux-persist-transform-encrypt/lib/helpers' {
  declare module.exports: any;
}

declare module '@tandem.ly/redux-persist-transform-encrypt/lib/sync' {
  declare module.exports: any;
}

// Filename aliases
declare module '@tandem.ly/redux-persist-transform-encrypt/async.js' {
  declare module.exports: $Exports<'@tandem.ly/redux-persist-transform-encrypt/async'>;
}
declare module '@tandem.ly/redux-persist-transform-encrypt/index' {
  declare module.exports: $Exports<'@tandem.ly/redux-persist-transform-encrypt'>;
}
declare module '@tandem.ly/redux-persist-transform-encrypt/index.js' {
  declare module.exports: $Exports<'@tandem.ly/redux-persist-transform-encrypt'>;
}
declare module '@tandem.ly/redux-persist-transform-encrypt/lib/async.js' {
  declare module.exports: $Exports<'@tandem.ly/redux-persist-transform-encrypt/lib/async'>;
}
declare module '@tandem.ly/redux-persist-transform-encrypt/lib/AsyncCryptor.js' {
  declare module.exports: $Exports<'@tandem.ly/redux-persist-transform-encrypt/lib/AsyncCryptor'>;
}
declare module '@tandem.ly/redux-persist-transform-encrypt/lib/helpers.js' {
  declare module.exports: $Exports<'@tandem.ly/redux-persist-transform-encrypt/lib/helpers'>;
}
declare module '@tandem.ly/redux-persist-transform-encrypt/lib/sync.js' {
  declare module.exports: $Exports<'@tandem.ly/redux-persist-transform-encrypt/lib/sync'>;
}
