// flow-typed signature: 31ebde17e70206123156637904641a36
// flow-typed version: <<STUB>>/bulma_v^0.5.3/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bulma'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bulma' {
  declare module.exports: any;
}
