// flow-typed signature: 4189d79af76030bc268bee29cd281bec
// flow-typed version: <<STUB>>/bulma_v^0.5.3/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bulma'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bulma' {
  declare module.exports: any;
}
