// flow-typed signature: 72d85454152ac95d4deb95775f9ba0e8
// flow-typed version: <<STUB>>/camelcase-object_v^1.0.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'camelcase-object'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'camelcase-object' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'camelcase-object/index' {
  declare module.exports: $Exports<'camelcase-object'>;
}
declare module 'camelcase-object/index.js' {
  declare module.exports: $Exports<'camelcase-object'>;
}
