// flow-typed signature: debd729ce6a6fc3df9ffdde05033887f
// flow-typed version: <<STUB>>/change-case-keys_v^0.0.4/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'change-case-keys'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'change-case-keys' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'change-case-keys/example/example' {
  declare module.exports: any;
}

// Filename aliases
declare module 'change-case-keys/example/example.js' {
  declare module.exports: $Exports<'change-case-keys/example/example'>;
}
declare module 'change-case-keys/index' {
  declare module.exports: $Exports<'change-case-keys'>;
}
declare module 'change-case-keys/index.js' {
  declare module.exports: $Exports<'change-case-keys'>;
}
