// flow-typed signature: 34e9badcb7923c42c5a23ce828f8f631
// flow-typed version: <<STUB>>/eosjs-ecc_v^1.6.1/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eosjs-ecc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eosjs-ecc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eosjs-ecc/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'eosjs-ecc/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'eosjs-ecc/dist/eosjs-ecc' {
  declare module.exports: any;
}

declare module 'eosjs-ecc/lib/aes' {
  declare module.exports: any;
}

declare module 'eosjs-ecc/lib/api_common' {
  declare module.exports: any;
}

declare module 'eosjs-ecc/lib/api_object' {
  declare module.exports: any;
}

declare module 'eosjs-ecc/lib/common.test' {
  declare module.exports: any;
}

declare module 'eosjs-ecc/lib/config' {
  declare module.exports: any;
}

declare module 'eosjs-ecc/lib/ecdsa' {
  declare module.exports: any;
}

declare module 'eosjs-ecc/lib/ecsignature' {
  declare module.exports: any;
}

declare module 'eosjs-ecc/lib/enforce_types' {
  declare module.exports: any;
}

declare module 'eosjs-ecc/lib/hash' {
  declare module.exports: any;
}

declare module 'eosjs-ecc/lib/index' {
  declare module.exports: any;
}

declare module 'eosjs-ecc/lib/index.test' {
  declare module.exports: any;
}

declare module 'eosjs-ecc/lib/key_private' {
  declare module.exports: any;
}

declare module 'eosjs-ecc/lib/key_public' {
  declare module.exports: any;
}

declare module 'eosjs-ecc/lib/key_utils' {
  declare module.exports: any;
}

declare module 'eosjs-ecc/lib/object.test' {
  declare module.exports: any;
}

declare module 'eosjs-ecc/lib/signature' {
  declare module.exports: any;
}

declare module 'eosjs-ecc/test/ecc' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eosjs-ecc/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'eosjs-ecc/coverage/lcov-report/prettify'>;
}
declare module 'eosjs-ecc/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'eosjs-ecc/coverage/lcov-report/sorter'>;
}
declare module 'eosjs-ecc/dist/eosjs-ecc.js' {
  declare module.exports: $Exports<'eosjs-ecc/dist/eosjs-ecc'>;
}
declare module 'eosjs-ecc/lib/aes.js' {
  declare module.exports: $Exports<'eosjs-ecc/lib/aes'>;
}
declare module 'eosjs-ecc/lib/api_common.js' {
  declare module.exports: $Exports<'eosjs-ecc/lib/api_common'>;
}
declare module 'eosjs-ecc/lib/api_object.js' {
  declare module.exports: $Exports<'eosjs-ecc/lib/api_object'>;
}
declare module 'eosjs-ecc/lib/common.test.js' {
  declare module.exports: $Exports<'eosjs-ecc/lib/common.test'>;
}
declare module 'eosjs-ecc/lib/config.js' {
  declare module.exports: $Exports<'eosjs-ecc/lib/config'>;
}
declare module 'eosjs-ecc/lib/ecdsa.js' {
  declare module.exports: $Exports<'eosjs-ecc/lib/ecdsa'>;
}
declare module 'eosjs-ecc/lib/ecsignature.js' {
  declare module.exports: $Exports<'eosjs-ecc/lib/ecsignature'>;
}
declare module 'eosjs-ecc/lib/enforce_types.js' {
  declare module.exports: $Exports<'eosjs-ecc/lib/enforce_types'>;
}
declare module 'eosjs-ecc/lib/hash.js' {
  declare module.exports: $Exports<'eosjs-ecc/lib/hash'>;
}
declare module 'eosjs-ecc/lib/index.js' {
  declare module.exports: $Exports<'eosjs-ecc/lib/index'>;
}
declare module 'eosjs-ecc/lib/index.test.js' {
  declare module.exports: $Exports<'eosjs-ecc/lib/index.test'>;
}
declare module 'eosjs-ecc/lib/key_private.js' {
  declare module.exports: $Exports<'eosjs-ecc/lib/key_private'>;
}
declare module 'eosjs-ecc/lib/key_public.js' {
  declare module.exports: $Exports<'eosjs-ecc/lib/key_public'>;
}
declare module 'eosjs-ecc/lib/key_utils.js' {
  declare module.exports: $Exports<'eosjs-ecc/lib/key_utils'>;
}
declare module 'eosjs-ecc/lib/object.test.js' {
  declare module.exports: $Exports<'eosjs-ecc/lib/object.test'>;
}
declare module 'eosjs-ecc/lib/signature.js' {
  declare module.exports: $Exports<'eosjs-ecc/lib/signature'>;
}
declare module 'eosjs-ecc/test/ecc.js' {
  declare module.exports: $Exports<'eosjs-ecc/test/ecc'>;
}
