// flow-typed signature: bd7dede5b9e727959cf3d115b5d6b3d3
// flow-typed version: <<STUB>>/eosjs_v4.0.2/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eosjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eosjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eosjs/dist/eos' {
  declare module.exports: any;
}

declare module 'eosjs/lib/abi-cache' {
  declare module.exports: any;
}

declare module 'eosjs/lib/format' {
  declare module.exports: any;
}

declare module 'eosjs/lib/format.test' {
  declare module.exports: any;
}

declare module 'eosjs/lib/index' {
  declare module.exports: any;
}

declare module 'eosjs/lib/index.test' {
  declare module.exports: any;
}

declare module 'eosjs/lib/structs' {
  declare module.exports: any;
}

declare module 'eosjs/lib/structs.test' {
  declare module.exports: any;
}

declare module 'eosjs/lib/write-api' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eosjs/dist/eos.js' {
  declare module.exports: $Exports<'eosjs/dist/eos'>;
}
declare module 'eosjs/lib/abi-cache.js' {
  declare module.exports: $Exports<'eosjs/lib/abi-cache'>;
}
declare module 'eosjs/lib/format.js' {
  declare module.exports: $Exports<'eosjs/lib/format'>;
}
declare module 'eosjs/lib/format.test.js' {
  declare module.exports: $Exports<'eosjs/lib/format.test'>;
}
declare module 'eosjs/lib/index.js' {
  declare module.exports: $Exports<'eosjs/lib/index'>;
}
declare module 'eosjs/lib/index.test.js' {
  declare module.exports: $Exports<'eosjs/lib/index.test'>;
}
declare module 'eosjs/lib/structs.js' {
  declare module.exports: $Exports<'eosjs/lib/structs'>;
}
declare module 'eosjs/lib/structs.test.js' {
  declare module.exports: $Exports<'eosjs/lib/structs.test'>;
}
declare module 'eosjs/lib/write-api.js' {
  declare module.exports: $Exports<'eosjs/lib/write-api'>;
}
