// flow-typed signature: a1221e8f63e5fc44d029853753699535
// flow-typed version: <<STUB>>/express-validation_v^1.0.2/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-validation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-validation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-validation/lib/index' {
  declare module.exports: any;
}

declare module 'express-validation/lib/validation-error' {
  declare module.exports: any;
}

declare module 'express-validation/test/app' {
  declare module.exports: any;
}

declare module 'express-validation/test/array' {
  declare module.exports: any;
}

declare module 'express-validation/test/body' {
  declare module.exports: any;
}

declare module 'express-validation/test/context' {
  declare module.exports: any;
}

declare module 'express-validation/test/cookies' {
  declare module.exports: any;
}

declare module 'express-validation/test/defaults' {
  declare module.exports: any;
}

declare module 'express-validation/test/errors' {
  declare module.exports: any;
}

declare module 'express-validation/test/headers' {
  declare module.exports: any;
}

declare module 'express-validation/test/mix' {
  declare module.exports: any;
}

declare module 'express-validation/test/options' {
  declare module.exports: any;
}

declare module 'express-validation/test/params' {
  declare module.exports: any;
}

declare module 'express-validation/test/parsing' {
  declare module.exports: any;
}

declare module 'express-validation/test/query' {
  declare module.exports: any;
}

declare module 'express-validation/test/register' {
  declare module.exports: any;
}

declare module 'express-validation/test/validation/account' {
  declare module.exports: any;
}

declare module 'express-validation/test/validation/array' {
  declare module.exports: any;
}

declare module 'express-validation/test/validation/context' {
  declare module.exports: any;
}

declare module 'express-validation/test/validation/defaults' {
  declare module.exports: any;
}

declare module 'express-validation/test/validation/index' {
  declare module.exports: any;
}

declare module 'express-validation/test/validation/login' {
  declare module.exports: any;
}

declare module 'express-validation/test/validation/logout' {
  declare module.exports: any;
}

declare module 'express-validation/test/validation/options' {
  declare module.exports: any;
}

declare module 'express-validation/test/validation/parsing' {
  declare module.exports: any;
}

declare module 'express-validation/test/validation/register' {
  declare module.exports: any;
}

declare module 'express-validation/test/validation/search' {
  declare module.exports: any;
}

declare module 'express-validation/test/validation/user' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-validation/lib/index.js' {
  declare module.exports: $Exports<'express-validation/lib/index'>;
}
declare module 'express-validation/lib/validation-error.js' {
  declare module.exports: $Exports<'express-validation/lib/validation-error'>;
}
declare module 'express-validation/test/app.js' {
  declare module.exports: $Exports<'express-validation/test/app'>;
}
declare module 'express-validation/test/array.js' {
  declare module.exports: $Exports<'express-validation/test/array'>;
}
declare module 'express-validation/test/body.js' {
  declare module.exports: $Exports<'express-validation/test/body'>;
}
declare module 'express-validation/test/context.js' {
  declare module.exports: $Exports<'express-validation/test/context'>;
}
declare module 'express-validation/test/cookies.js' {
  declare module.exports: $Exports<'express-validation/test/cookies'>;
}
declare module 'express-validation/test/defaults.js' {
  declare module.exports: $Exports<'express-validation/test/defaults'>;
}
declare module 'express-validation/test/errors.js' {
  declare module.exports: $Exports<'express-validation/test/errors'>;
}
declare module 'express-validation/test/headers.js' {
  declare module.exports: $Exports<'express-validation/test/headers'>;
}
declare module 'express-validation/test/mix.js' {
  declare module.exports: $Exports<'express-validation/test/mix'>;
}
declare module 'express-validation/test/options.js' {
  declare module.exports: $Exports<'express-validation/test/options'>;
}
declare module 'express-validation/test/params.js' {
  declare module.exports: $Exports<'express-validation/test/params'>;
}
declare module 'express-validation/test/parsing.js' {
  declare module.exports: $Exports<'express-validation/test/parsing'>;
}
declare module 'express-validation/test/query.js' {
  declare module.exports: $Exports<'express-validation/test/query'>;
}
declare module 'express-validation/test/register.js' {
  declare module.exports: $Exports<'express-validation/test/register'>;
}
declare module 'express-validation/test/validation/account.js' {
  declare module.exports: $Exports<'express-validation/test/validation/account'>;
}
declare module 'express-validation/test/validation/array.js' {
  declare module.exports: $Exports<'express-validation/test/validation/array'>;
}
declare module 'express-validation/test/validation/context.js' {
  declare module.exports: $Exports<'express-validation/test/validation/context'>;
}
declare module 'express-validation/test/validation/defaults.js' {
  declare module.exports: $Exports<'express-validation/test/validation/defaults'>;
}
declare module 'express-validation/test/validation/index.js' {
  declare module.exports: $Exports<'express-validation/test/validation/index'>;
}
declare module 'express-validation/test/validation/login.js' {
  declare module.exports: $Exports<'express-validation/test/validation/login'>;
}
declare module 'express-validation/test/validation/logout.js' {
  declare module.exports: $Exports<'express-validation/test/validation/logout'>;
}
declare module 'express-validation/test/validation/options.js' {
  declare module.exports: $Exports<'express-validation/test/validation/options'>;
}
declare module 'express-validation/test/validation/parsing.js' {
  declare module.exports: $Exports<'express-validation/test/validation/parsing'>;
}
declare module 'express-validation/test/validation/register.js' {
  declare module.exports: $Exports<'express-validation/test/validation/register'>;
}
declare module 'express-validation/test/validation/search.js' {
  declare module.exports: $Exports<'express-validation/test/validation/search'>;
}
declare module 'express-validation/test/validation/user.js' {
  declare module.exports: $Exports<'express-validation/test/validation/user'>;
}
