// flow-typed signature: 688cc7076a86fcb6ee651a8b0b23230c
// flow-typed version: <<STUB>>/jest-fetch-mock_v^1.2.1/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-fetch-mock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-fetch-mock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-fetch-mock/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-fetch-mock/src/index.js' {
  declare module.exports: $Exports<'jest-fetch-mock/src/index'>;
}
