// flow-typed signature: 4cb09da6dcef03603ab4f4614928a163
// flow-typed version: <<STUB>>/nano-md5_v^1.0.3/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nano-md5'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nano-md5' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nano-md5/md5' {
  declare module.exports: any;
}

declare module 'nano-md5/test/md5' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nano-md5/md5.js' {
  declare module.exports: $Exports<'nano-md5/md5'>;
}
declare module 'nano-md5/test/md5.js' {
  declare module.exports: $Exports<'nano-md5/test/md5'>;
}
