// flow-typed signature: a3cf2651c88d60f68abdd7afc0ed6ab3
// flow-typed version: <<STUB>>/randomatic_v^2.0.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'randomatic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'randomatic' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'randomatic/index' {
  declare module.exports: $Exports<'randomatic'>;
}
declare module 'randomatic/index.js' {
  declare module.exports: $Exports<'randomatic'>;
}
