// flow-typed signature: e711823791085dd17d709a305e66e912
// flow-typed version: <<STUB>>/react-styleable_v^3.2.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-styleable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-styleable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-styleable/lib/__specs__/styleable.spec' {
  declare module.exports: any;
}

declare module 'react-styleable/lib/styleable' {
  declare module.exports: any;
}

declare module 'react-styleable/lib/utils/get-display-name' {
  declare module.exports: any;
}

declare module 'react-styleable/test/utils/babel-register' {
  declare module.exports: any;
}

declare module 'react-styleable/test/utils/dom' {
  declare module.exports: any;
}

declare module 'react-styleable/test/utils/node-extensions' {
  declare module.exports: any;
}

declare module 'react-styleable/test/utils/react-warnings' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-styleable/index' {
  declare module.exports: $Exports<'react-styleable'>;
}
declare module 'react-styleable/index.js' {
  declare module.exports: $Exports<'react-styleable'>;
}
declare module 'react-styleable/lib/__specs__/styleable.spec.js' {
  declare module.exports: $Exports<'react-styleable/lib/__specs__/styleable.spec'>;
}
declare module 'react-styleable/lib/styleable.js' {
  declare module.exports: $Exports<'react-styleable/lib/styleable'>;
}
declare module 'react-styleable/lib/utils/get-display-name.js' {
  declare module.exports: $Exports<'react-styleable/lib/utils/get-display-name'>;
}
declare module 'react-styleable/test/utils/babel-register.js' {
  declare module.exports: $Exports<'react-styleable/test/utils/babel-register'>;
}
declare module 'react-styleable/test/utils/dom.js' {
  declare module.exports: $Exports<'react-styleable/test/utils/dom'>;
}
declare module 'react-styleable/test/utils/node-extensions.js' {
  declare module.exports: $Exports<'react-styleable/test/utils/node-extensions'>;
}
declare module 'react-styleable/test/utils/react-warnings.js' {
  declare module.exports: $Exports<'react-styleable/test/utils/react-warnings'>;
}
