// flow-typed signature: 431f3ef74a15616e5cf43d533cfff785
// flow-typed version: <<STUB>>/redux-form-validators_v^2.1.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-form-validators'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-form-validators' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-form-validators/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'redux-form-validators/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'redux-form-validators/dist/redux-form-validator' {
  declare module.exports: any;
}

declare module 'redux-form-validators/dist/redux-form-validators.min' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/__tests__/absence.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/__tests__/acceptance.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/__tests__/add-validator.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/__tests__/allow-blank.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/__tests__/confirmation.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/__tests__/date.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/__tests__/email.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/__tests__/exclusion.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/__tests__/format-message.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/__tests__/format.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/__tests__/helper' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/__tests__/if-unless.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/__tests__/inclusion.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/__tests__/length.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/__tests__/memoize.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/__tests__/messages.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/__tests__/numericality.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/__tests__/presence.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/__tests__/setup' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/__tests__/url.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/absence' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/acceptance' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/add-validator' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/confirmation' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/date' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/email' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/exclusion' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/format' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/helpers' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/inclusion' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/index' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/length' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/messages' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/numericality' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/presence' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/redux-form-validators' {
  declare module.exports: any;
}

declare module 'redux-form-validators/lib/url' {
  declare module.exports: any;
}

declare module 'redux-form-validators/postcss.config' {
  declare module.exports: any;
}

declare module 'redux-form-validators/registerBabel' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/__tests__/absence.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/__tests__/acceptance.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/__tests__/add-validator.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/__tests__/allow-blank.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/__tests__/confirmation.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/__tests__/date.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/__tests__/email.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/__tests__/exclusion.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/__tests__/format-message.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/__tests__/format.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/__tests__/helper' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/__tests__/if-unless.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/__tests__/inclusion.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/__tests__/length.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/__tests__/memoize.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/__tests__/messages.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/__tests__/numericality.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/__tests__/presence.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/__tests__/setup' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/__tests__/url.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/absence' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/acceptance' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/add-validator' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/confirmation' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/date' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/email' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/exclusion' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/format' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/helpers' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/inclusion' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/index' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/length' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/messages' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/numericality' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/presence' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/redux-form-validators' {
  declare module.exports: any;
}

declare module 'redux-form-validators/src/url' {
  declare module.exports: any;
}

declare module 'redux-form-validators/translationRunner' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-form-validators/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'redux-form-validators/coverage/lcov-report/prettify'>;
}
declare module 'redux-form-validators/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'redux-form-validators/coverage/lcov-report/sorter'>;
}
declare module 'redux-form-validators/dist/redux-form-validator.js' {
  declare module.exports: $Exports<'redux-form-validators/dist/redux-form-validator'>;
}
declare module 'redux-form-validators/dist/redux-form-validators.min.js' {
  declare module.exports: $Exports<'redux-form-validators/dist/redux-form-validators.min'>;
}
declare module 'redux-form-validators/lib/__tests__/absence.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/__tests__/absence.spec'>;
}
declare module 'redux-form-validators/lib/__tests__/acceptance.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/__tests__/acceptance.spec'>;
}
declare module 'redux-form-validators/lib/__tests__/add-validator.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/__tests__/add-validator.spec'>;
}
declare module 'redux-form-validators/lib/__tests__/allow-blank.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/__tests__/allow-blank.spec'>;
}
declare module 'redux-form-validators/lib/__tests__/confirmation.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/__tests__/confirmation.spec'>;
}
declare module 'redux-form-validators/lib/__tests__/date.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/__tests__/date.spec'>;
}
declare module 'redux-form-validators/lib/__tests__/email.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/__tests__/email.spec'>;
}
declare module 'redux-form-validators/lib/__tests__/exclusion.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/__tests__/exclusion.spec'>;
}
declare module 'redux-form-validators/lib/__tests__/format-message.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/__tests__/format-message.spec'>;
}
declare module 'redux-form-validators/lib/__tests__/format.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/__tests__/format.spec'>;
}
declare module 'redux-form-validators/lib/__tests__/helper.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/__tests__/helper'>;
}
declare module 'redux-form-validators/lib/__tests__/if-unless.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/__tests__/if-unless.spec'>;
}
declare module 'redux-form-validators/lib/__tests__/inclusion.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/__tests__/inclusion.spec'>;
}
declare module 'redux-form-validators/lib/__tests__/length.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/__tests__/length.spec'>;
}
declare module 'redux-form-validators/lib/__tests__/memoize.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/__tests__/memoize.spec'>;
}
declare module 'redux-form-validators/lib/__tests__/messages.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/__tests__/messages.spec'>;
}
declare module 'redux-form-validators/lib/__tests__/numericality.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/__tests__/numericality.spec'>;
}
declare module 'redux-form-validators/lib/__tests__/presence.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/__tests__/presence.spec'>;
}
declare module 'redux-form-validators/lib/__tests__/setup.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/__tests__/setup'>;
}
declare module 'redux-form-validators/lib/__tests__/url.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/__tests__/url.spec'>;
}
declare module 'redux-form-validators/lib/absence.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/absence'>;
}
declare module 'redux-form-validators/lib/acceptance.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/acceptance'>;
}
declare module 'redux-form-validators/lib/add-validator.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/add-validator'>;
}
declare module 'redux-form-validators/lib/confirmation.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/confirmation'>;
}
declare module 'redux-form-validators/lib/date.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/date'>;
}
declare module 'redux-form-validators/lib/email.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/email'>;
}
declare module 'redux-form-validators/lib/exclusion.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/exclusion'>;
}
declare module 'redux-form-validators/lib/format.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/format'>;
}
declare module 'redux-form-validators/lib/helpers.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/helpers'>;
}
declare module 'redux-form-validators/lib/inclusion.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/inclusion'>;
}
declare module 'redux-form-validators/lib/index.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/index'>;
}
declare module 'redux-form-validators/lib/length.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/length'>;
}
declare module 'redux-form-validators/lib/messages.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/messages'>;
}
declare module 'redux-form-validators/lib/numericality.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/numericality'>;
}
declare module 'redux-form-validators/lib/presence.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/presence'>;
}
declare module 'redux-form-validators/lib/redux-form-validators.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/redux-form-validators'>;
}
declare module 'redux-form-validators/lib/url.js' {
  declare module.exports: $Exports<'redux-form-validators/lib/url'>;
}
declare module 'redux-form-validators/postcss.config.js' {
  declare module.exports: $Exports<'redux-form-validators/postcss.config'>;
}
declare module 'redux-form-validators/registerBabel.js' {
  declare module.exports: $Exports<'redux-form-validators/registerBabel'>;
}
declare module 'redux-form-validators/src/__tests__/absence.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/src/__tests__/absence.spec'>;
}
declare module 'redux-form-validators/src/__tests__/acceptance.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/src/__tests__/acceptance.spec'>;
}
declare module 'redux-form-validators/src/__tests__/add-validator.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/src/__tests__/add-validator.spec'>;
}
declare module 'redux-form-validators/src/__tests__/allow-blank.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/src/__tests__/allow-blank.spec'>;
}
declare module 'redux-form-validators/src/__tests__/confirmation.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/src/__tests__/confirmation.spec'>;
}
declare module 'redux-form-validators/src/__tests__/date.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/src/__tests__/date.spec'>;
}
declare module 'redux-form-validators/src/__tests__/email.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/src/__tests__/email.spec'>;
}
declare module 'redux-form-validators/src/__tests__/exclusion.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/src/__tests__/exclusion.spec'>;
}
declare module 'redux-form-validators/src/__tests__/format-message.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/src/__tests__/format-message.spec'>;
}
declare module 'redux-form-validators/src/__tests__/format.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/src/__tests__/format.spec'>;
}
declare module 'redux-form-validators/src/__tests__/helper.js' {
  declare module.exports: $Exports<'redux-form-validators/src/__tests__/helper'>;
}
declare module 'redux-form-validators/src/__tests__/if-unless.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/src/__tests__/if-unless.spec'>;
}
declare module 'redux-form-validators/src/__tests__/inclusion.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/src/__tests__/inclusion.spec'>;
}
declare module 'redux-form-validators/src/__tests__/length.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/src/__tests__/length.spec'>;
}
declare module 'redux-form-validators/src/__tests__/memoize.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/src/__tests__/memoize.spec'>;
}
declare module 'redux-form-validators/src/__tests__/messages.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/src/__tests__/messages.spec'>;
}
declare module 'redux-form-validators/src/__tests__/numericality.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/src/__tests__/numericality.spec'>;
}
declare module 'redux-form-validators/src/__tests__/presence.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/src/__tests__/presence.spec'>;
}
declare module 'redux-form-validators/src/__tests__/setup.js' {
  declare module.exports: $Exports<'redux-form-validators/src/__tests__/setup'>;
}
declare module 'redux-form-validators/src/__tests__/url.spec.js' {
  declare module.exports: $Exports<'redux-form-validators/src/__tests__/url.spec'>;
}
declare module 'redux-form-validators/src/absence.js' {
  declare module.exports: $Exports<'redux-form-validators/src/absence'>;
}
declare module 'redux-form-validators/src/acceptance.js' {
  declare module.exports: $Exports<'redux-form-validators/src/acceptance'>;
}
declare module 'redux-form-validators/src/add-validator.js' {
  declare module.exports: $Exports<'redux-form-validators/src/add-validator'>;
}
declare module 'redux-form-validators/src/confirmation.js' {
  declare module.exports: $Exports<'redux-form-validators/src/confirmation'>;
}
declare module 'redux-form-validators/src/date.js' {
  declare module.exports: $Exports<'redux-form-validators/src/date'>;
}
declare module 'redux-form-validators/src/email.js' {
  declare module.exports: $Exports<'redux-form-validators/src/email'>;
}
declare module 'redux-form-validators/src/exclusion.js' {
  declare module.exports: $Exports<'redux-form-validators/src/exclusion'>;
}
declare module 'redux-form-validators/src/format.js' {
  declare module.exports: $Exports<'redux-form-validators/src/format'>;
}
declare module 'redux-form-validators/src/helpers.js' {
  declare module.exports: $Exports<'redux-form-validators/src/helpers'>;
}
declare module 'redux-form-validators/src/inclusion.js' {
  declare module.exports: $Exports<'redux-form-validators/src/inclusion'>;
}
declare module 'redux-form-validators/src/index.js' {
  declare module.exports: $Exports<'redux-form-validators/src/index'>;
}
declare module 'redux-form-validators/src/length.js' {
  declare module.exports: $Exports<'redux-form-validators/src/length'>;
}
declare module 'redux-form-validators/src/messages.js' {
  declare module.exports: $Exports<'redux-form-validators/src/messages'>;
}
declare module 'redux-form-validators/src/numericality.js' {
  declare module.exports: $Exports<'redux-form-validators/src/numericality'>;
}
declare module 'redux-form-validators/src/presence.js' {
  declare module.exports: $Exports<'redux-form-validators/src/presence'>;
}
declare module 'redux-form-validators/src/redux-form-validators.js' {
  declare module.exports: $Exports<'redux-form-validators/src/redux-form-validators'>;
}
declare module 'redux-form-validators/src/url.js' {
  declare module.exports: $Exports<'redux-form-validators/src/url'>;
}
declare module 'redux-form-validators/translationRunner.js' {
  declare module.exports: $Exports<'redux-form-validators/translationRunner'>;
}
