// flow-typed signature: 59e0fb9c25fef8c1c23a5f6d514049e9
// flow-typed version: <<STUB>>/redux-persist-cookie-storage_v^0.4.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-persist-cookie-storage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-persist-cookie-storage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-persist-cookie-storage/src/fake-cookie-jar' {
  declare module.exports: any;
}

declare module 'redux-persist-cookie-storage/src/redux-persist-cookie-storage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-persist-cookie-storage/index' {
  declare module.exports: $Exports<'redux-persist-cookie-storage'>;
}
declare module 'redux-persist-cookie-storage/index.js' {
  declare module.exports: $Exports<'redux-persist-cookie-storage'>;
}
declare module 'redux-persist-cookie-storage/src/fake-cookie-jar.js' {
  declare module.exports: $Exports<'redux-persist-cookie-storage/src/fake-cookie-jar'>;
}
declare module 'redux-persist-cookie-storage/src/redux-persist-cookie-storage.js' {
  declare module.exports: $Exports<'redux-persist-cookie-storage/src/redux-persist-cookie-storage'>;
}
