// flow-typed signature: cfeb50355253cdfb22dcdf853c03e7e9
// flow-typed version: <<STUB>>/snakecase-keys_v^1.1.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'snakecase-keys'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'snakecase-keys' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'snakecase-keys/index' {
  declare module.exports: $Exports<'snakecase-keys'>;
}
declare module 'snakecase-keys/index.js' {
  declare module.exports: $Exports<'snakecase-keys'>;
}
